function tree = trainClassTree( inputs, outputs, splitmin, varargin )
% TRAINCLASSTREE Trains a decision tree using the treefit command of
% statistics toolbox. The tree pruning is off.

    tree = classregtree( inputs, outputs, ...
        varargin{:}, ...
        'method', 'classification', ...
        'prune', 'off', ...
        'splitmin', splitmin );

end