create or replace
PROCEDURE DEMO_NAPLN_SEMESTRY AS 
-- created - Sobota-únor-12-2011 Ivan Halaska
-- dalsi upravy:
begin
            declare V_POM PLS_INTEGER;
            begin select COUNT(*) into V_POM from DEMO_SEMESTR;
                  if V_POM > 0 then DBMS_OUTPUT.PUT_LINE('Tabulka DEMO_SEMESTR není prázdná, konèím');  
                  return;
                  end if;
            end;
INSERT INTO  DEMO_SEMESTR(SEMESTR_ID, NAZEV_SEMESTRU) VALUES(091, 'Zimní semestr 2009/10');
INSERT INTO  DEMO_SEMESTR(SEMESTR_ID, NAZEV_SEMESTRU) VALUES(101, 'Zimní semestr 2010/11');
INSERT INTO  DEMO_SEMESTR(SEMESTR_ID, NAZEV_SEMESTRU) VALUES(111, 'Zimní semestr 2011/12');
INSERT INTO  DEMO_SEMESTR(SEMESTR_ID, NAZEV_SEMESTRU) VALUES(121, 'Zimní semestr 2012/13');
INSERT INTO  DEMO_SEMESTR(SEMESTR_ID, NAZEV_SEMESTRU) VALUES(131, 'Zimní semestr 2013/14');
INSERT INTO  DEMO_SEMESTR(SEMESTR_ID, NAZEV_SEMESTRU) VALUES(141, 'Zimní semestr 2014/15');
INSERT INTO  DEMO_SEMESTR(SEMESTR_ID, NAZEV_SEMESTRU) VALUES(151, 'Zimní semestr 2015/16');
INSERT INTO  DEMO_SEMESTR(SEMESTR_ID, NAZEV_SEMESTRU) VALUES(161, 'Zimní semestr 2016/17');
INSERT INTO  DEMO_SEMESTR(SEMESTR_ID, NAZEV_SEMESTRU) VALUES(171, 'Zimní semestr 2017/18');
INSERT INTO  DEMO_SEMESTR(SEMESTR_ID, NAZEV_SEMESTRU) VALUES(181, 'Zimní semestr 2018/19');
INSERT INTO  DEMO_SEMESTR(SEMESTR_ID, NAZEV_SEMESTRU) VALUES(191, 'Zimní semestr 2019/20');
INSERT INTO  DEMO_SEMESTR(SEMESTR_ID, NAZEV_SEMESTRU) VALUES(201, 'Zimní semestr 2020/21');
INSERT INTO  DEMO_SEMESTR(SEMESTR_ID, NAZEV_SEMESTRU) VALUES(211, 'Zimní semestr 2021/22');
-- letni semestry
INSERT INTO  DEMO_SEMESTR(SEMESTR_ID, NAZEV_SEMESTRU) VALUES(092, 'Letní semestr 2009/10');
INSERT INTO  DEMO_SEMESTR(SEMESTR_ID, NAZEV_SEMESTRU) VALUES(102, 'Letní semestr 2010/11');
INSERT INTO  DEMO_SEMESTR(SEMESTR_ID, NAZEV_SEMESTRU) VALUES(112, 'Letní semestr 2011/12');
INSERT INTO  DEMO_SEMESTR(SEMESTR_ID, NAZEV_SEMESTRU) VALUES(122, 'Letní semestr 2012/13');
INSERT INTO  DEMO_SEMESTR(SEMESTR_ID, NAZEV_SEMESTRU) VALUES(132, 'Letní semestr 2013/14');
INSERT INTO  DEMO_SEMESTR(SEMESTR_ID, NAZEV_SEMESTRU) VALUES(142, 'Letní semestr 2014/15');
INSERT INTO  DEMO_SEMESTR(SEMESTR_ID, NAZEV_SEMESTRU) VALUES(152, 'Letní semestr 2015/16');
INSERT INTO  DEMO_SEMESTR(SEMESTR_ID, NAZEV_SEMESTRU) VALUES(162, 'Letní semestr 2016/17');
INSERT INTO  DEMO_SEMESTR(SEMESTR_ID, NAZEV_SEMESTRU) VALUES(172, 'Letní semestr 2017/18');
INSERT INTO  DEMO_SEMESTR(SEMESTR_ID, NAZEV_SEMESTRU) VALUES(182, 'Letní semestr 2018/19');
INSERT INTO  DEMO_SEMESTR(SEMESTR_ID, NAZEV_SEMESTRU) VALUES(192, 'Letní semestr 2019/20');
INSERT INTO  DEMO_SEMESTR(SEMESTR_ID, NAZEV_SEMESTRU) VALUES(202, 'Letní semestr 2020/21');
INSERT INTO  DEMO_SEMESTR(SEMESTR_ID, NAZEV_SEMESTRU) VALUES(212, 'Letní semestr 2021/22');
commit;
declare 
V_POM PLS_INTEGER; 
begin
select COUNT(*) into V_POM from DEMO_SEMESTR;
DBMS_OUTPUT.PUT_LINE('Do tabulky DEMO_SEMESTR bylo vlo¾eno '||V_POM||' øádkù');
end;
END DEMO_NAPLN_SEMESTRY;