
.PHONY: test clean

all: test

test:
	python DU3Tester.pyc main.cpp

clean:
	rm compilerLog
	rm pytel
	rm output1
	rm output-ref1
	rm output2
	rm output-ref2
	rm output3
	rm output-ref3
	rm output4
	rm output-ref4

