
/*
 * 
 */

package cz.ctu.fee.murinrad.ifaceserver;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1
 * Sun Dec 09 23:32:37 CET 2012
 * Generated source version: 2.3.1
 * 
 */


@WebServiceClient(name = "InterfaceServiceService", 
                  wsdlLocation = "http://murko2-pc:8080/InterfaceServer/InterfaceServiceService?wsdl",
                  targetNamespace = "http://interfaceserver.murinrad.fee.ctu.cz/") 
public class InterfaceServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://interfaceserver.murinrad.fee.ctu.cz/", "InterfaceServiceService");
    public final static QName InterfaceServicePort = new QName("http://interfaceserver.murinrad.fee.ctu.cz/", "InterfaceServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://murko2-pc:8080/InterfaceServer/InterfaceServiceService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://murko2-pc:8080/InterfaceServer/InterfaceServiceService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public InterfaceServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public InterfaceServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InterfaceServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public InterfaceServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }
    public InterfaceServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public InterfaceServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InterfaceServiceIface
     */
    @WebEndpoint(name = "InterfaceServicePort")
    public InterfaceServiceIface getInterfaceServicePort() {
        return super.getPort(InterfaceServicePort, InterfaceServiceIface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InterfaceServiceIface
     */
    @WebEndpoint(name = "InterfaceServicePort")
    public InterfaceServiceIface getInterfaceServicePort(WebServiceFeature... features) {
        return super.getPort(InterfaceServicePort, InterfaceServiceIface.class, features);
    }

}
