
package cz.ctu.fee.murinrad.ifaceserver;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.3.1
 * Sun Dec 09 23:32:37 CET 2012
 * Generated source version: 2.3.1
 * 
 */

@WebFault(name = "PaymentException", targetNamespace = "http://interfaceserver.murinrad.fee.ctu.cz/")
public class PaymentException_Exception extends Exception {
    public static final long serialVersionUID = 20121209233237L;
    
    private cz.ctu.fee.murinrad.ifaceserver.PaymentException paymentException;

    public PaymentException_Exception() {
        super();
    }
    
    public PaymentException_Exception(String message) {
        super(message);
    }
    
    public PaymentException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public PaymentException_Exception(String message, cz.ctu.fee.murinrad.ifaceserver.PaymentException paymentException) {
        super(message);
        this.paymentException = paymentException;
    }

    public PaymentException_Exception(String message, cz.ctu.fee.murinrad.ifaceserver.PaymentException paymentException, Throwable cause) {
        super(message, cause);
        this.paymentException = paymentException;
    }

    public cz.ctu.fee.murinrad.ifaceserver.PaymentException getFaultInfo() {
        return this.paymentException;
    }
}
