
package cz.ctu.fee.murinrad.ifaceserver;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.3.1
 * Sun Dec 09 23:32:36 CET 2012
 * Generated source version: 2.3.1
 * 
 */

@WebFault(name = "PrintingException", targetNamespace = "http://interfaceserver.murinrad.fee.ctu.cz/")
public class PrintingException_Exception extends Exception {
    public static final long serialVersionUID = 20121209233236L;
    
    private cz.ctu.fee.murinrad.ifaceserver.PrintingException printingException;

    public PrintingException_Exception() {
        super();
    }
    
    public PrintingException_Exception(String message) {
        super(message);
    }
    
    public PrintingException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public PrintingException_Exception(String message, cz.ctu.fee.murinrad.ifaceserver.PrintingException printingException) {
        super(message);
        this.printingException = printingException;
    }

    public PrintingException_Exception(String message, cz.ctu.fee.murinrad.ifaceserver.PrintingException printingException, Throwable cause) {
        super(message, cause);
        this.printingException = printingException;
    }

    public cz.ctu.fee.murinrad.ifaceserver.PrintingException getFaultInfo() {
        return this.printingException;
    }
}
