
package cz.ctu.fee.murinrad.ifaceserver;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.3.1
 * Sun Dec 09 23:32:36 CET 2012
 * Generated source version: 2.3.1
 * 
 */

@WebFault(name = "ReservationException", targetNamespace = "http://interfaceserver.murinrad.fee.ctu.cz/")
public class ReservationException_Exception extends Exception {
    public static final long serialVersionUID = 20121209233236L;
    
    private cz.ctu.fee.murinrad.ifaceserver.ReservationException reservationException;

    public ReservationException_Exception() {
        super();
    }
    
    public ReservationException_Exception(String message) {
        super(message);
    }
    
    public ReservationException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ReservationException_Exception(String message, cz.ctu.fee.murinrad.ifaceserver.ReservationException reservationException) {
        super(message);
        this.reservationException = reservationException;
    }

    public ReservationException_Exception(String message, cz.ctu.fee.murinrad.ifaceserver.ReservationException reservationException, Throwable cause) {
        super(message, cause);
        this.reservationException = reservationException;
    }

    public cz.ctu.fee.murinrad.ifaceserver.ReservationException getFaultInfo() {
        return this.reservationException;
    }
}
