
package cz.ctu.fee.murinrad.ifaceserver;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.3.1
 * Sun Dec 09 23:32:36 CET 2012
 * Generated source version: 2.3.1
 * 
 */

@WebFault(name = "SearchException", targetNamespace = "http://interfaceserver.murinrad.fee.ctu.cz/")
public class SearchException_Exception extends Exception {
    public static final long serialVersionUID = 20121209233236L;
    
    private cz.ctu.fee.murinrad.ifaceserver.SearchException searchException;

    public SearchException_Exception() {
        super();
    }
    
    public SearchException_Exception(String message) {
        super(message);
    }
    
    public SearchException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public SearchException_Exception(String message, cz.ctu.fee.murinrad.ifaceserver.SearchException searchException) {
        super(message);
        this.searchException = searchException;
    }

    public SearchException_Exception(String message, cz.ctu.fee.murinrad.ifaceserver.SearchException searchException, Throwable cause) {
        super(message, cause);
        this.searchException = searchException;
    }

    public cz.ctu.fee.murinrad.ifaceserver.SearchException getFaultInfo() {
        return this.searchException;
    }
}
